version: '2'
services:
    salaryfs-app:
        image: salaryfs
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://salaryfs-postgresql:5432/salaryfs
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    salaryfs-postgresql:
        extends:
            file: postgresql.yml
            service: salaryfs-postgresql
